NumPy is the fundamental package for scientific computing with Python. It contains among other things:

  * a powerful N-dimensional array object
  * sophisticated (broadcasting) functions
  * tools for integrating C/C++ and Fortran code
  * useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined and this allows NumPy to seamlessly and speedily integrate with a wide variety of projects



In [ ]:
import numpy as np # importing convention

# Arrays

A numpy array is a grid of values, **all of the same type**, and is indexed by a tuple of nonnegative integers

With respect to standard python lists, Numpy provides:
* extension package to Python for multi-dimensional arrays
* closer to hardware (efficiency)
* designed for scientific computation (convenience)
* Also known as array oriented computing


All standard data types are available:

In [78]:
# type can be set
a=np.array([1, 2, 3],'float64')
print (a,a.dtype,'\n')
a=np.array([1, 2, 3],'uint32')
print (a,a.dtype,'\n')

# or inferred: 

# complex
a=np.array([1+2j, 3+4j, 5+6*1j])
print (a,a.dtype,'\n')

# bool
a = np.array([True, False, False, True])
print (a,a.dtype,'\n')

# string
a=np.array(['bonjour messieurs dames', 'Hello', 'Hallo'])
print (a,a.dtype,'\n')


[1. 2. 3.] float64 

[1 2 3] uint32 

[1.+2.j 3.+4.j 5.+6.j] complex128 

[ True False False  True] bool 

['bonjour messieurs dames' 'Hello' 'Hallo'] <U23 



Arrays are memory-efficient container that provides fast numerical operations

In [16]:
# standard python
L = range(1000)
%timeit [i**2 for i in L]

# numpy
a = np.arange(1000)
%timeit a**2


372 µs ± 7.55 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.22 µs ± 19.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Dimensions

The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

1D containers

In [31]:
a1 = np.array([0, 1, 2, 3])
print (a1)
print ("array dimensions (rank):", a1.ndim)
print ("shape of the array:", a1.shape)
print ("size of the first dimension (axis):", len(a1))

[0 1 2 3]
array dimensions (rank): 1
shape of the array: (4,)
size of the first dimension (axis): 4


2D, 3D and so on

In [44]:
a2_3 = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array (dim x raws x columns)
print ("2 x 3 array:") 
print (a2_3)
print ("array dimensions (rank):", a2_3.ndim)
print ("shape of the array:", a2_3.shape)
print ("size of the first dimension (axis):", len(a2_3))

print ("")

a3_2_2 = np.array([[[1,10], [2,20], [3,30]], [[4,40], [5,50], [6,60]]])# 2 x 3 x 2 array (dim x raws x columns)
print ("2 x 3 x 2 array:")
print (a3_2_2)
print ("array dimensions (rank):", a3_2_2.ndim)
print ("shape of the array:", a3_2_2.shape)
print ("size of the first dimension (axis):", len(a3_2_2))


2 x 3 array:
[[0 1 2]
 [3 4 5]]
array dimensions (rank): 2
shape of the array: (2, 3)
size of the first dimension (axis): 2

2 x 3 x 2 array:
[[[ 1 10]
  [ 2 20]
  [ 3 30]]

 [[ 4 40]
  [ 5 50]
  [ 6 60]]]
array dimensions (rank): 3
shape of the array: (2, 3, 2)
size of the first dimension (axis): 2


### Generating arrays

In [51]:
# evenly spaced:
print (np.arange(1,9,2)) # same as "range": start, end (exclusive), step

# or by number of points:
print (np.linspace(0, 1, 20)) # start, end, num-points (to be used for plotting f(x))


[1 3 5 7]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [59]:
# 3x3 matrix of 1's
ones = np.ones((3, 3))
print (ones,'\n')

# 2x2 matrix of 0's
zeros = np.zeros((2, 2))
print (zeros,'\n')

# 3x3 unitary matrix
unity3d = np.eye(3)
print (unity3d,'\n')

# generic diagonal matrix
diagonal = np.diag(np.array([1, 20, 3, 4]))
print (diagonal,'\n')

# from lists
array = np.array([(i,j) for i in range(2) for j in range(3)])
print (array,'\n')

# from a function
fromfunct = np.fromfunction(lambda i, j: (i-2)**2+(j-i)**2, (5,5))
print (fromfunct,'\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0.]
 [0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[ 1  0  0  0]
 [ 0 20  0  0]
 [ 0  0  3  0]
 [ 0  0  0  4]] 

[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]] 

[[ 4.  5.  8. 13. 20.]
 [ 2.  1.  2.  5. 10.]
 [ 4.  1.  0.  1.  4.]
 [10.  5.  2.  1.  2.]
 [20. 13.  8.  5.  4.]] 



In [65]:
## more on random later!

# Setting the random seed
np.random.seed(1235)        

# filling an array with random numers
uniform = np.random.rand(4) # 4 random numbers in [0,1]
print (uniform,'\n')

gaussian = np.random.randn(5) # 5 random numbers drawn from a gaussian with mean=0 and sigma=1
print (gaussian,'\n')

[0.95376258 0.99212647 0.47960292 0.94340686] 

[ 0.66805361  0.48883782 -0.67978825 -1.30747938  1.47030437] 



## Indexing and slicing

The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):

In [80]:
a = np.arange(10)
print (a[0], a[2], a[-1])

# reminder: the [start:stop:step] works as well. 
# step can be negative and a reverse sequence is thus obtained
print (a[2:9:3])
print (a[::-1])


0 2 9
[9 8 7 6 5 4 3 2 1 0]


In [89]:
#! wget https://www.dropbox.com/s/vgy4mmdm7jd00xd/numpy_indexing.png
from IPython.display import Image
Image(url="numpy_indexing.png")

For multidimensional arrays, indexes are tuples of integers.

Note:
* in 2D, the first dimension corresponds to rows, the second to columns.
* for multidimensional a, a[0] is interpreted by taking all elements in the unspecified dimensions.

In [90]:
a = np.diag(np.arange(3))
print (a,'\n')
print (a[1,1],'\n')
print (a[2],'\n')

# assignment
a[2, 1] = 10 # third line, second column
print (a,'\n')

[[0 0 0]
 [0 1 0]
 [0 0 2]] 

1 

[0 0 2] 

[[ 0  0  0]
 [ 0  1  0]
 [ 0 10  2]] 



A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use `np.may_share_memory()` to check if two arrays share the same memory block. Note however, that this uses heuristics and may give you false positives.

When modifying the view, the original array is modified as well, watch out!