In [6]:
import numpy as np
import math
import matplotlib.pyplot as pl

In [ ]:
#Esercizio 1
m = np.arange(12).reshape((3,4))
print("The matrix is",m)
for i in range(m.shape[0]):
    print(i,"-th row mean is:", np.mean(m[i,:]))
for j in range(m.shape[1]):
    print(j,"-th column mean is:", np.mean(m[:,j]))
print("Overall mean is:", np.mean(m))

In [ ]:
#Esercizio 2
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])

p1 = np.outer(u,v)
p2 = np.array([u[i]*v[j] for i in range(4) for j in range(4)]).reshape(4,4)
p3 = u.reshape(4,1)*v
print(p1)
print(p2)
print(p3)

In [ ]:
#Esercizio 3
x = np.random.rand(10,6)
x[x < 0.1] = 0
print(x)

In [ ]:
#Esercizio 4
x = np.linspace(0,2*math.pi,100)
sliced = x[:10:]
rev = x[::-1]
closesc = x[np.abs(np.sin(x)-np.cos(x))<0.1]
pl.figure()
pl.plot(x, np.sin(x))
pl.plot(x, np.cos(x))
pl.scatter(closesc, np.sin(closesc))
pl.show()

In [ ]:
#Esercizio 5
nums = np.arange(1,11)
mtab = np.outer(nums,nums)
tr = np.sum(np.diag(mtab))
adiag = np.diag(mtab[:,::-1])
print(mtab)
print(tr)
print(adiag)
mask = np.fromfunction(lambda i,j: i == j-1, (10,10))
print(mtab[mask])

In [ ]:
#Esercizio 6
dist = np.array([ 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
grid = (-np.tile(dist,(10,1)).T + dist)*1.60934
print(grid)

In [ ]:
#Esercizio 7
N = 99
numbers = np.arange(0,N+1)
mask = np.ones(N+1,dtype=bool)


In [ ]:
#Esercizio 8

def sampleJumps(N):
    return np.array([-1 if np.random.rand() < 0.5 else 1 for x in range(N)])
walkersN = 1000
iters = 20

expDist = np.zeros(iters)
for t in range(iters):
    steps = t*200   
    rwalk = np.array([sampleJumps(steps) for x in range(walkersN)])
    distances = np.zeros(walkersN)
    for w in range(walkersN):
        distances[w] = np.abs(np.sum(rwalk[w,:]))
    expDist[t] = np.mean(distances**2)
pl.plot(np.arange(iters)*200, expDist)
pl.show()

In [26]:
#Esercizio 9
import csv

x = []
names = []
with open('populations.txt') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter='	')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            names = row
            line_count += 1
        else:
            x.append(np.array(row, dtype=float))
            line_count += 1
print(names)


['# year', 'hare', 'lynx', 'carrot']
[  1900.  30000.   4000.  48300.]
[  1901.  47200.   6100.  48200.]
[  1902.  70200.   9800.  41500.]
[  1903.  77400.  35200.  38200.]
[  1904.  36300.  59400.  40600.]
[  1905.  20600.  41700.  39800.]
[  1906.  18100.  19000.  38600.]
[  1907.  21400.  13000.  42300.]
[  1908.  22000.   8300.  44500.]
[  1909.  25400.   9100.  42100.]
[  1910.  27100.   7400.  46000.]
[  1911.  40300.   8000.  46800.]
[  1912.  57000.  12300.  43800.]
[  1913.  76600.  19500.  40900.]
[  1914.  52300.  45700.  39400.]
[  1915.  19500.  51100.  39000.]
[  1916.  11200.  29700.  36700.]
[  1917.   7600.  15800.  41800.]
[  1918.  14600.   9700.  43300.]
[  1919.  16200.  10100.  41300.]
[  1920.  24700.   8600.  47300.]
