### Numpy basics

In [2]:
import numpy as np

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [39]:
#1 senza usare le funzioni

m = np.arange(12).reshape((3,4))
#print(m)
shape = m.shape

row_m = np.zeros((shape[0],1))
col_m = np.zeros((shape[1],1))
overall_m = 0.

#media dei valori in ogni riga
for i in range(shape[0]):
    for j in range(shape[1]):
        row_m[i] += m[i,j]
row_m /= shape[1]
print("Vecor of row means:\n", row_m)

#media dei valori in ogni colonna
for i in range(shape[1]):
    for j in range(shape[0]):
        col_m[i] += m[j,i]
col_m /= shape[0]
print("Vecor of column means:\n", col_m)

#media complessiva
for i in range(shape[0]):
    for j in range(shape[1]):
        overall_m += m[i,j]
overall_m /= (shape[0]*shape[1])
print("Overall mean:", overall_m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Vecor of row means:
 [[1.5]
 [5.5]
 [9.5]]
Vecor of column means:
 [[4.]
 [5.]
 [6.]
 [7.]]
verall mean: 5.5


In [43]:
#1 usando le funzioni di numpy

print("Row means:\n", m.mean(axis=1))
print("Column means:\n", m.mean(axis=0))
print("Overall mean:", m.mean())


Row means:
 [1.5 5.5 9.5]
Column means:
 [4. 5. 6. 7.]
Overall mean: 5.5


2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


In [45]:
#2.a
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])

w = np.outer(u,v)
#print(w)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [74]:
#2.b.con il for
shape_u = u.shape
shape_v = v.shape
w = np.zeros((shape_u[0],shape_v[0]))

for i in range(shape_u[0]):
    for j in range(shape_v[0]):
        w[i,j] = u[i]*v[j]
print(w)

#2.b con una lista 
z = np.array([u[i]*v[j] for i in range(shape_u[0]) for j in range(shape_v[0])]).reshape((shape_u[0],shape_v[0]))
print(z)

[[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [89]:
#2.3
u_t = np.array([u]).T #traspone il primo vettore

print("Matrix created by broadcasting:\n", u_t*v)

Matrix created by broadcasting:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

In [78]:
#3

m = np.random.random((10,6))


[[0.33983462 0.29750077 0.57687936 0.11753148 0.50937845 0.957223  ]
 [0.85147438 0.82561121 0.74327891 0.06026451 0.95021067 0.4985473 ]
 [0.38115198 0.26531903 0.20839038 0.11867331 0.5124764  0.02596294]
 [0.35552342 0.2702609  0.18723014 0.50894374 0.19138764 0.27132186]
 [0.2717619  0.53463288 0.55062395 0.96439722 0.15105699 0.93662968]
 [0.826239   0.921847   0.99114958 0.62026129 0.66877705 0.66441987]
 [0.49656196 0.07118002 0.08131222 0.15090578 0.32224597 0.88999721]
 [0.50566637 0.68909592 0.38246759 0.14617317 0.7393692  0.0494926 ]
 [0.77628483 0.70459795 0.73629805 0.87940328 0.48603227 0.69505622]
 [0.20464932 0.28021628 0.44067621 0.00866107 0.33932737 0.17429764]]


4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.