In [5]:
import numpy as np
import pandas as pd
from scipy import linalg as la
from scipy import stats
from matplotlib import pyplot as plt
%matplotlib inline
#from matplotlib.ticker import AutoMinorLocator, MultipleLocator, FuncFormatter
#import seaborn as sns

1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that they are two procedure yields to same result
* What percent of the total variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [75]:
x1=np.random.normal(0, 1, 1000)
x2=x1+np.random.normal(0, 3, 1000)
x3=2*x1+x2
data = pd.DataFrame(
    { 'x1' : x1,
      'x2' : x2,
      'x3' : x3,
    }
    )
data

x1        x2         x3
0    1.716107  0.852863   4.285077
1   -0.553477 -4.019568  -5.126522
2    0.782507  5.032375   6.597388
3   -1.028497 -4.300463  -6.357457
4   -0.680380 -2.104214  -3.464974
5    0.260760 -6.031062  -5.509543
6   -1.862402 -5.536014  -9.260817
7   -0.018197 -3.125550  -3.161944
8    1.476033  4.362691   7.314757
9    0.152357  1.357075   1.661789
10  -2.467288 -6.187122 -11.121698
11   0.276382 -0.966630  -0.413867
12  -1.711425  1.981978  -1.440872
13  -2.244264 -0.466058  -4.954585
14  -0.255089 -1.917212  -2.427390
15   1.583548 -1.422310   1.744787
16  -1.838606 -1.535277  -5.212488
17  -0.827206  3.376851   1.722438
18  -0.134545  1.302345   1.033254
19   1.190157 -4.156715  -1.776402
20   1.708760  5.785735   9.203255
21  -0.421774 -0.658647  -1.502196
22   0.457585  0.342877   1.258046
23  -0.002035 -2.403358  -2.407429
24   0.002629 -4.155855  -4.150597
25   0.298217  2.053803   2.650237
26   1.213080 -0.180562   2.245597
27  -0.052053  0.561610   0.457504
28   0.019974 -1.169857  -1.129909
29   0.229187  2.095617   2.553990
..        ...       ...        ...
970  0.565154 -3.268359  -2.138050
971 -0.251980 -0.185702  -0.689661
972 -0.087686  0.204113   0.028741
973 -1.815026 -2.707622  -6.337673
974  0.803363 -0.021990   1.584736
975 -0.228078 -0.356599  -0.812755
976  0.229439  0.721887   1.180766
977 -1.112705 -3.310456  -5.535866
978  0.053658 -2.002649  -1.895332
979  0.214332  4.195939   4.624603
980  0.979653  4.362778   6.322083
981 -1.024484  0.588270  -1.460698
982  0.608780 -1.393352  -0.175792
983  1.361918 -0.923047   1.800790
984 -0.410169  3.015005   2.194666
985  0.003063  0.653630   0.659756
986 -0.834952 -1.714358  -3.384262
987 -0.308822  0.683619   0.065974
988  0.213307  1.565632   1.992246
989  0.247463 -0.227305   0.267620
990 -0.431797 -6.611619  -7.475213
991  0.506742  5.350275   6.363759
992  1.046184  2.063786   4.156153
993 -0.194212  0.236958  -0.151467
994 -1.208020 -6.377441  -8.793481
995 -0.362708 -3.687994  -4.413411
996  0.097892  1.641499   1.837283
997 -1.255749 -4.246696  -6.758193
998 -1.572762  1.216020  -1.929504
999 -0.769345 -3.047282  -4.585973

[1000 rows x 3 columns]

In [87]:
c=np.cov(data, rowvar=False)
print("Covariance matrix:")
print(c)
l, V = la.eig(c)
print("\nCovariance matrix again with eigenvalues-eigenvectors decomposition:")
print(np.dot(V,np.dot(np.diag(l), la.inv(V))))
print("\nEigenvectors:","\nFirst->",V[0],"\nSecond->",V[1],"\nThird->",V[2])
print("\nEigenvalues:",l)
U, spectrum, Vt = la.svd(c)
print("\nCovariance matrix again with singular value decomposition:")
print(np.dot(U,np.dot(np.diag(spectrum), Vt)))
print("\nEigenvalues with SVD:",spectrum) #they are in non decreasing order
                                          #the last one is different since the machine precision is 1e-16

print("\nWeight of first eigenvalue:",spectrum[0]/spectrum.sum())
print("\nWeight of second eigenvalue:",spectrum[1]/spectrum.sum())
print("\nWeight of first+second eigenvalue:",(spectrum[0]+spectrum[1])/spectrum.sum())


#general case
threshold=0.99
i=1
while ((spectrum[:i].sum())/(spectrum.sum()))<threshold:
    i+=1
#Reducing the dimensionality to k<p simply means setting to zero all but first k diagonal values
spectrum[i:len(spectrum)]=0
print("\nTo keep the "+str(threshold*100)+"% we need",i,"eigenvalues")



print("\nRotate the data to obtain a trivial column:")
datarot=np.dot(data,U) #the last column becomes all 1e-16 which means zero
pd.DataFrame(datarot)


Covariance matrix:
[[ 0.98076416  0.90825825  2.86978657]
 [ 0.90825825  9.07383894 10.89035545]
 [ 2.86978657 10.89035545 16.62992859]]

Covariance matrix again with eigenvalues-eigenvectors decomposition:
[[ 0.98076416+0.j  0.90825825+0.j  2.86978657+0.j]
 [ 0.90825825+0.j  9.07383894+0.j 10.89035545+0.j]
 [ 2.86978657+0.j 10.89035545+0.j 16.62992859+0.j]]

Eigenvectors: 
First-> [-0.11996478 -0.81649658  0.56474931] 
Second-> [-0.57170905 -0.40824829 -0.71167556] 
Third-> [-0.8116386   0.40824829  0.41782307]

Eigenvalues: [ 2.47251425e+01+0.j -1.83875423e-15+0.j  1.95938922e+00+0.j]

Covariance matrix again with singular value decomposition:
[[ 0.98076416  0.90825825  2.86978657]
 [ 0.90825825  9.07383894 10.89035545]
 [ 2.86978657 10.89035545 16.62992859]]

Eigenvalues with SVD: [2.47251425e+01 1.95938922e+00 3.95797547e-16]

Weight of first eigenvalue: 0.926572096234674

Weight of second eigenvalue: 0.07342790376532611

Weight of first+second eigenvalue: 1.0

To keep the 99.0% we

0         1             2
0    -4.171396  2.152613 -1.394845e-15
1     6.525304  0.406074  7.766757e-16
2    -8.325622 -0.382957 -1.197793e-15
3     7.741955 -0.176601  1.229390e-15
4     4.096927 -0.334473  7.105476e-16
5     7.888489  2.137409  2.005330e-16
6    10.904848 -0.981327  1.761328e-15
7     4.355444  0.892968  2.567848e-16
8    -8.608201  0.785042 -1.386493e-15
9    -2.142901 -0.185420 -2.888704e-16
10   12.860021 -1.637077  2.959139e-15
11    0.855386  0.671090 -1.288510e-16
12    0.241664 -2.979081  1.272925e-15
13    4.557015 -3.005904  1.956573e-15
14    3.096853  0.206152  2.891307e-16
15   -0.792959  2.635543 -1.175206e-15
16    5.328956 -2.123630  1.378310e-15
17   -3.229338 -2.150712  4.614753e-16
18   -1.567050 -0.571114  1.082948e-17
19    3.675451  2.888151 -7.558227e-16
20  -10.982465  0.692787 -1.768841e-15
21    1.646392 -0.397106  4.065380e-16
22   -1.271999  0.540044 -3.512237e-16
23    3.328228  0.703383  4.694396e-17
24    5.744409  1.224889  1.609442e-16
25   -3.360988 -0.185893 -2.466026e-16
26   -1.864911  1.751850 -1.002899e-15
27   -0.686161 -0.237925  8.520776e-18
28    1.583499  0.371736  1.594794e-17
29   -3.298494 -0.294850 -2.509871e-16
..         ...       ...           ...
970   3.536076  1.751855 -3.756054e-16
971   0.696151 -0.298302  2.427303e-16
972  -0.129501 -0.182774  6.138099e-17
973   6.909611 -1.746112  1.439498e-15
974  -1.370037  1.131488 -6.768514e-16
975   0.890895 -0.214611  2.066534e-16
976  -1.398589  0.109178 -2.465989e-16
977   6.519226 -0.585442  1.228860e-15
978   2.676820  0.663626  1.362283e-16
979  -6.178074 -0.932838 -5.039894e-16
980  -7.743010  0.089888 -1.097077e-15
981   0.972141 -1.607548  7.238397e-16
982   0.866239  1.261972 -3.936046e-16
983  -1.097258  2.178464 -1.085306e-15
984  -3.455776 -1.460366  1.407474e-16
985  -0.909537 -0.187781 -4.140129e-17
986   3.827076 -0.665494  6.842959e-16
987  -0.407331 -0.633357  2.235461e-16
988  -2.537659 -0.161351 -3.659659e-16
989  -0.116945  0.413340 -1.583675e-16
990   9.898895  1.338154  3.772921e-16
991  -8.284664 -0.862552 -7.402560e-16
992  -4.678685  0.858622 -1.136504e-15
993   0.010764 -0.341605  1.480931e-16
994  10.928089  0.182321  1.749028e-15
995   5.734066  0.575791  3.973113e-16
996  -2.441414 -0.345271 -2.059338e-16
997   8.063730 -0.510643  1.124168e-15
998   1.059526 -2.559819  1.139514e-15
999   5.556605 -0.181936  8.056450e-16

[1000 rows x 3 columns]

In [85]:
datarot2=datarot[:,0:2] #I don't want the last column since is always zero
pd.DataFrame(datarot2)

0         1
0    -4.171396  2.152613
1     6.525304  0.406074
2    -8.325622 -0.382957
3     7.741955 -0.176601
4     4.096927 -0.334473
5     7.888489  2.137409
6    10.904848 -0.981327
7     4.355444  0.892968
8    -8.608201  0.785042
9    -2.142901 -0.185420
10   12.860021 -1.637077
11    0.855386  0.671090
12    0.241664 -2.979081
13    4.557015 -3.005904
14    3.096853  0.206152
15   -0.792959  2.635543
16    5.328956 -2.123630
17   -3.229338 -2.150712
18   -1.567050 -0.571114
19    3.675451  2.888151
20  -10.982465  0.692787
21    1.646392 -0.397106
22   -1.271999  0.540044
23    3.328228  0.703383
24    5.744409  1.224889
25   -3.360988 -0.185893
26   -1.864911  1.751850
27   -0.686161 -0.237925
28    1.583499  0.371736
29   -3.298494 -0.294850
..         ...       ...
970   3.536076  1.751855
971   0.696151 -0.298302
972  -0.129501 -0.182774
973   6.909611 -1.746112
974  -1.370037  1.131488
975   0.890895 -0.214611
976  -1.398589  0.109178
977   6.519226 -0.585442
978   2.676820  0.663626
979  -6.178074 -0.932838
980  -7.743010  0.089888
981   0.972141 -1.607548
982   0.866239  1.261972
983  -1.097258  2.178464
984  -3.455776 -1.460366
985  -0.909537 -0.187781
986   3.827076 -0.665494
987  -0.407331 -0.633357
988  -2.537659 -0.161351
989  -0.116945  0.413340
990   9.898895  1.338154
991  -8.284664 -0.862552
992  -4.678685  0.858622
993   0.010764 -0.341605
994  10.928089  0.182321
995   5.734066  0.575791
996  -2.441414 -0.345271
997   8.063730 -0.510643
998   1.059526 -2.559819
999   5.556605 -0.181936

[1000 rows x 2 columns]

2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset