1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that they are two procedure yields to same result
* What percent of the total variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [7]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
from scipy import linalg as la
import scipy as sp
from math import pi
from math import e
%matplotlib inline

#creo il dataset:

x1=np.random.normal(0,1,1000)
x2=x1+np.random.normal(0,3,1000)
x3= 2*x1+x2

dataset=np.array([x1,x2,x3])
dataset.shape
#print(dataset)
cov=np.cov(dataset)
print('\nla matrice di covarianza: \n\n',cov)
#autovalori e vettori
va,vett=la.eig(cov)
print('autovalori: \n \n',va,'\n autovettori \n \n',vett)

#usando SVD
U, spectrum, Vt = la.svd(cov)
print('\n autovalori \n \n',spectrum,'\n autovettori: \n \n',U)

#variabilità rimasta togliendo l'autovalore minore:
variability=(spectrum.sum()-spectrum.min())/spectrum.sum()
print(variability*100,' %')

print('spiegazione: il fatto che due autovalori siano sufficienti a spiegare tutta la variabilità è perchè ho slo due variabili linearmente indipendenti')

#riduzione con PCA
'''dataset_r=np.array([x1,x2])
cov_r=np.cov(dataset_r)
va_r,vett_r=la.eig(cov_r)
print('autovalori: \n \n',va_r,'\n autovettori \n \n',vett_r)'''


la matrice di covarianza: 

 [[ 1.04474832  1.01568867  3.10518532]
 [ 1.01568867 10.31947931 12.35085665]
 [ 3.10518532 12.35085665 18.56122728]]
autovalori: 
 
 [ 2.78229530e+01+0.j -6.85957255e-16+0.j  2.10250189e+00+0.j] 
 autovettori 
 
 [[-0.11563408 -0.81649658  0.56565192]
 [-0.5771452  -0.40824829 -0.70727417]
 [-0.80841337  0.40824829  0.42402967]]

 autovalori 
 
 [2.78229530e+01 2.10250189e+00 2.72287228e-16] 
 autovettori: 
 
 [[-0.11563408  0.56565192 -0.81649658]
 [-0.5771452  -0.70727417 -0.40824829]
 [-0.80841337  0.42402967  0.40824829]]
100.0  %
spiegazione: il fatto che due autovalori siano sufficienti a spiegare tutta la variabilità è perchè ho slo due variabili linearmente indipendenti
autovalori: 
 
 [ 0.93482173+0.j 10.42940591+0.j] 
 autovettori 
 
 [[-0.99419424 -0.10760028]
 [ 0.10760028 -0.99419424]]


2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset