1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that they are two procedure yields to same result
* What percent of the total variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg as la

In [42]:
N = 1000
mean = 0.
std = 1.
x1 = np.random.normal(0., 1., N)
x2 = x1 + np.random.normal(0., 3., N)
x3 = 2*x1 + x2

x123 = np.array([x1, x2, x3])

# print(np.dot(x123, x123.T)/(N-1))       # Sbagliata perché non considero le medie effettive

cov_x123 = np.cov(x123)

print("Covariance matricx:\n", cov_x123, "\n")

spectrum_np, eig_V_np = la.eig(cov_x123)

print("Spectrum is:\n", spectrum_np, "\n")
print("Eigenvectors matrix is:\n", eig_V_np, "\n")

eig_V_sci, spectrum_sci, eig_U_sci = la.svd(cov_x123)

print("Spectrum is:\n", spectrum_sci, "\n")
print("Eigenvectors matrix is:\n", eig_V_sci, "\n")

perc_first = spectrum_sci.max()/np.sum(spectrum_sci)

print("Percentage of the first (greater) eigenvalue:\n", perc_first, "\n")

#######################################

perc_99 = 0
i = 0

while perc_99 < 0.99:
    perc_99 += spectrum_sci[i]/np.sum(spectrum_sci)
    i += 1

spectrum_sci[i:] = 0

# print("New spectrum (99%) is:\n", spectrum_sci, "\n")

'''
# Re-building initial cov matrix
#Diag_sci = np.zeros((len(spectrum_sci), len(scpectrum_sci)))
#for ele in len(spectrum_sci):
#    Diag_sci[]

Diag_sci = np.diag(spectrum_sci)

print("The diagonal (new) matrix is:\n", Diag_sci, "\n")

cov_PCA = eig_V_sci.dot(Diag_sci.dot(eig_V_sci.T))

print("Covariance matrix after PCA (reconstructed):\n", cov_PCA, "\n")
'''
###########################################

x123_rot = eig_V_sci.T.dot(x123)

print("Printing rotated data:\n", x123_rot, "\n")

# Deleting the "smallest" row

x123_rot = x123_rot[:i]         # N.B.: SVD gives a matrix with ordered eigen-vectors, so one can simply remove
                                #       remove the last rows

print(x123_rot)

Covariance matricx:
 [[ 1.01342485  0.89862191  2.92547161]
 [ 0.89862191  9.07871399 10.87595781]
 [ 2.92547161 10.87595781 16.72690103]] 

Spectrum is:
 [2.47874278e+01+0.j 1.81386812e-15+0.j 2.03161209e+00+0.j] 

Eigenvectors matrix is:
 [[-0.12155312 -0.81649658  0.56440958]
 [-0.56970462 -0.40824829 -0.71328113]
 [-0.81281085  0.40824829  0.41553802]] 

Spectrum is:
 [2.47874278e+01 2.03161209e+00 2.50862656e-15] 

Eigenvectors matrix is:
 [[-0.12155312  0.56440958 -0.81649658]
 [-0.56970462 -0.71328113 -0.40824829]
 [-0.81281085  0.41553802  0.40824829]] 

Percentage of the first (greater) eigenvalue:
 0.9242473966645286 

Printing rotated data:
 [[-7.87172486e+00  1.83310762e+00 -5.19249201e+00 ... -4.22763595e+00
   9.78511885e-02 -2.54406518e+00]
 [ 1.01821142e+00 -1.04301648e+00 -2.86333190e-01 ... -3.61896465e+00
  -1.78952596e+00  7.87488055e-01]
 [-1.48970422e-15  9.88548973e-16 -5.97589943e-17 ...  2.63958624e-15
   1.60608443e-15 -7.78720552e-16]] 

[[-7.87172486  1.8331

2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset