1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that they are two procedure yields to same result
* What percent of the total variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [15]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
from scipy import linalg as la
%matplotlib inline

In [54]:
# Generate normal distribution according to the problem
N = 5*10**3
x1 = np.random.normal(loc=0, scale=1, size=N)
x2 = x1 + np.random.normal(loc=0, scale=3, size=N)
x3 = 2*x1 + x2
X = np.vstack((x1,x2,x3))
cov = np.cov(X)

# Find eigenvectors and eigenvalues
lambdas, V = la.eig(cov)
print('Eigenvalues:\n',lambdas)
print('Eigenvectors:\n',V)

# Do the SVD decomposition on the original dataset X
U, spectrum, Vt = la.svd(X)
print('Eigenvalues with SVD:\n',spectrum**2/(N-1))
print('Eigenvectors with SVD:\n',U)



Eigenvalues:
 [2.58014561e+01+0.j 1.53936721e-17+0.j 1.99007442e+00+0.j]
Eigenvectors:
 [[-0.1167515  -0.81649658  0.56542234]
 [-0.57574661 -0.40824829 -0.70841314]
 [-0.80924961  0.40824829  0.42243154]]
Eigenvalues with SVD:
 [2.58079576e+01 1.99067816e+00 1.44429295e-31]
Eigenvectors with SVD:
 [[-0.11679854  0.56541262 -0.81649658]
 [-0.57568767 -0.70846104 -0.40824829]
 [-0.80928475  0.42236421  0.40824829]]


2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset